In [1]:
import  pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [2]:
df_cbf = pd.read_csv('data/cbf_df.csv')

In [3]:
lista_compilado = df_cbf["geral"].tolist()

print(lista_compilado)

['Adventure Animation Children Comedy Fantasy pixar pixar fun 1995', 'Adventure Children Fantasy fantasy magic board game Robin Williams game 1995', 'Comedy Romance moldy old 1995', 'Comedy Drama Romance  1995', 'Comedy pregnancy remake 1995', 'Action Crime Thriller  1995', 'Comedy Romance remake 1995', 'Adventure Children  1995', 'Action  1995', 'Action Adventure Thriller  1995', 'Comedy Drama Romance politics president 1995', 'Comedy Horror  1995', 'Adventure Animation Children  1995', 'Drama politics president 1995', 'Action Adventure Romance  1995', 'Crime Drama Mafia 1995', 'Drama Romance Jane Austen 1995', 'Comedy  1995', 'Comedy  1995', 'Action Comedy Crime Drama Thriller  1995', 'Comedy Crime Thriller Hollywood 1995', 'Crime Drama Horror Mystery Thriller serial killer 1995', 'Action Crime Thriller  1995', 'Drama Sci-Fi  1995', 'Drama Romance alcoholism 1995', 'Drama Shakespeare 1995', 'Children Drama  1995', 'Drama Romance In Netflix queue Jane Austen 1995', 'Adventure Drama Fa

In [4]:
cvec = CountVectorizer(stop_words='english', ngram_range=(1,2))

sf = cvec.fit_transform(lista_compilado)

###matriz de vocabulario do documento
print(sf.toarray())

### Vocabulários obtidos após o aprendizado (função Fit)
cvec.vocabulary_

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


{'adventure': 291,
 'animation': 467,
 'children': 1232,
 'comedy': 1438,
 'fantasy': 2883,
 'pixar': 5424,
 'fun': 3318,
 '1995': 103,
 'adventure animation': 322,
 'animation children': 504,
 'children comedy': 1274,
 'comedy fantasy': 1583,
 'fantasy pixar': 2983,
 'pixar pixar': 5429,
 'pixar fun': 5428,
 'fun 1995': 3319,
 'magic': 4534,
 'board': 932,
 'game': 3373,
 'robin': 5958,
 'williams': 8002,
 'adventure children': 327,
 'children fantasy': 1280,
 'fantasy fantasy': 2963,
 'fantasy magic': 2975,
 'magic board': 4535,
 'board game': 933,
 'game robin': 3376,
 'robin williams': 5959,
 'williams game': 8008,
 'game 1995': 3374,
 'romance': 5988,
 'moldy': 4732,
 'old': 5243,
 'comedy romance': 1634,
 'romance moldy': 6208,
 'moldy old': 4733,
 'old 1995': 5244,
 'drama': 2305,
 'comedy drama': 1571,
 'drama romance': 2587,
 'romance 1995': 6056,
 'pregnancy': 5543,
 'remake': 5876,
 'comedy pregnancy': 1622,
 'pregnancy remake': 5548,
 'remake 1995': 5880,
 'action': 176,
 '

In [5]:
transformer = TfidfTransformer()
tfidf_matrix = transformer.fit_transform(sf)
print(tfidf_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 65738 stored elements and shape (9708, 8093)>
  Coords	Values
  (0, 103)	0.15613223513619742
  (0, 291)	0.10246734838464966
  (0, 322)	0.1573301434192229
  (0, 467)	0.12699067015046553
  (0, 504)	0.15070814235253852
  (0, 1232)	0.1238855731929086
  (0, 1274)	0.14461278022933477
  (0, 1438)	0.0657152190948466
  (0, 1583)	0.1591391870775104
  (0, 2883)	0.11880723748074866
  (0, 2983)	0.3200903451750936
  (0, 3318)	0.2778252057929909
  (0, 3319)	0.3200903451750936
  (0, 5424)	0.5783539019295438
  (0, 5428)	0.3200903451750936
  (0, 5429)	0.3200903451750936
  (1, 103)	0.12110088218991485
  (1, 291)	0.07947677348126021
  (1, 327)	0.13460367819900282
  (1, 932)	0.24827174956769316
  (1, 933)	0.24827174956769316
  (1, 1232)	0.09608939621710641
  (1, 1280)	0.14616549369064763
  (1, 2883)	0.18430097099314208
  (1, 2963)	0.22429438635958365
  :	:
  (9703, 211)	0.4037611516395078
  (9703, 467)	0.25494230388020334
  (9703, 505)	0.3705717

In [11]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
(cosine_sim.shape)

(9708, 9708)

In [26]:
df_ratings_count = pd.read_csv('data/movies_ratings_count.csv')

list_ratings_count = df_ratings_count.loc[:, 'count_ratings'].to_list()

list_ratings_count = np.array(list_ratings_count)

list_ratings_count.shape

log_ratings = np.log1p(list_ratings_count)
log_ratings


# 2. Normalização Min-Max (coloca tudo entre 0 e 1)
# Subtraímos o mínimo e dividimos pela amplitude (max - min)
pop_score = (log_ratings - log_ratings.min()) / (log_ratings.max() - log_ratings.min())
pop_score.shape

(9708,)

In [24]:
# Supondo que 'cos_sim' seja o array de resultados do seu TF-IDF/Cosseno
peso_conteudo = 0.8
peso_popularidade = 0.2

# O resultado final será um novo array com os scores ajustados
score_final = (cosine_sim * peso_conteudo) + (pop_score * peso_popularidade)


score_final

array([[0.98538343, 0.21110453, 0.16735504, ..., 0.02390537, 0.05176887,
        0.03545668],
       [0.23406495, 0.962423  , 0.15697651, ..., 0.02390537, 0.02390537,
        0.02390537],
       [0.21581043, 0.18247147, 0.93692804, ..., 0.02390537, 0.02390537,
        0.03921563],
       ...,
       [0.18538343, 0.162423  , 0.13692804, ..., 0.82390537, 0.02390537,
        0.02390537],
       [0.21324693, 0.162423  , 0.13692804, ..., 0.02390537, 0.82390537,
        0.02390537],
       [0.19693474, 0.162423  , 0.1522383 , ..., 0.02390537, 0.02390537,
        0.82390537]], shape=(9708, 9708))

In [7]:
def recomendar_filmes(titulo_filme, movies_df, cosine_sim_matrix, n_recomendacoes=10):
    print(f'gerando recomendações para filme {titulo_filme}\n')
    indices = pd.Series(movies_df.index, index=movies_df['titulo_movie_lens']).drop_duplicates()
    
    if titulo_filme not in indices:
        print(f"Filme '{titulo_filme}' não encontrado no dataset.")
        return pd.Series([])

    idx = indices[titulo_filme]

    sim_scores = list(enumerate(cosine_sim_matrix[idx]))



    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:n_recomendacoes + 1]  

    filme_indices = [i[0] for i in sim_scores]
    print(f"filmes similares ao {titulo_filme}")
    print(movies_df['titulo_movie_lens'].iloc[filme_indices].to_string(index=False))
    return movies_df['titulo_movie_lens'].iloc[filme_indices]



filme = "Toy Story (1995)"
recomendados = recomendar_filmes(filme, df_cbf, cosine_sim)





gerando recomendações para filme Toy Story (1995)

filmes similares ao Toy Story (1995)
                              Bug's Life, A (1998)
                                Toy Story 2 (1999)
                    Tale of Despereaux, The (2008)
                                  Wild, The (2006)
Asterix and the Vikings (Astérix et les Vikings...
                          The Good Dinosaur (2015)
                            Shrek the Third (2007)
                                      Moana (2016)
                                      Turbo (2013)
                             Monsters, Inc. (2001)


In [8]:
def recomendar_filmes_perfil(user_id, movies_df, cosine_sim_matrix, n_recomendacoes=50, df_traing_path='data_spliting/traing.csv'):
    # 1. Carregar o histórico de treino do usuário
    df_traing = pd.read_csv(df_traing_path)
    
    print('######################################################')
    print(f' Coletando perfil do usuário {user_id} ')
    print('######################################################\n')

    # 2. Identificar os IDs dos filmes que o usuário já assistiu
    df_user = df_traing.loc[df_traing['userId'] == user_id]
    list_id_movies = df_user['movieId'].to_list()

    # 3. Mapear esses IDs para os índices numéricos da matriz de similaridade
    # Filtramos o movies_df para encontrar onde esses IDs estão localizados
    indices_usuario = movies_df[movies_df['movieId'].isin(list_id_movies)].index.tolist()

    if not indices_usuario:
        # print(f"Aviso: Nenhum filme do histórico do usuário {user_id} foi encontrado no catálogo.")
        return pd.DataFrame()

    # 4. Cálculo da Recomendação por Perfil (Média de Similaridade)
    # Criamos um vetor de zeros com o tamanho do catálogo
    sim_scores_total = np.zeros(cosine_sim_matrix.shape[0])
    
    # Somamos os vetores de similaridade de cada filme assistido
    for idx in indices_usuario:
        sim_scores_total += cosine_sim_matrix[idx]
    
    # Criamos a lista de (índice, score)
    sim_scores = list(enumerate(sim_scores_total))
    
    # Ordenamos pelos scores mais altos
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # 5. Filtragem: Remover filmes que o usuário já assistiu
    sim_scores_filtrados = [s for s in sim_scores if s[0] not in indices_usuario]

    # 6. Selecionar o Top N
    top_sim_scores = sim_scores_filtrados[:n_recomendacoes]
    filme_indices = [i[0] for i in top_sim_scores]

    # 7. Gerar o resultado com ID e Título
    print(f"Filmes recomendados para o perfil do usuário {user_id}:")
    # Selecionamos as colunas desejadas usando iloc com os índices encontrados
    recomendacoes = movies_df.iloc[filme_indices][['movieId', 'titulo_movie_lens']]
    
    return recomendacoes



In [12]:
# from tqdm import tqdm

# resultados = {}
# for i in tqdm(range(1, 600)):
#     resultados[i] = recomendar_filmes_perfil(i, df_cbf, cosine_sim)

# recomenados.to_csv('recomenados-1.csv', index=False)

recomendados = recomendar_filmes_perfil(1, df_cbf, cosine_sim)

print(recomendados)

recomendados.to_csv('lista_user_1.csv')

######################################################
 Coletando perfil do usuário 1 
######################################################

Filmes recomendados para o perfil do usuário 1:
      movieId                                  titulo_movie_lens
6863    62383                20,000 Leagues Under the Sea (1916)
6455    52287                          Meet the Robinsons (2007)
1164     1544              Lost World: Jurassic Park, The (1997)
1044     1356                    Star Trek: First Contact (1996)
5620    27155                  Batman/Superman Movie, The (1998)
4348     6350  Laputa: Castle in the Sky (Tenkû no shiro Rapy...
5533    26590                         G.I. Joe: The Movie (1987)
5868    32898  Trip to the Moon, A (Voyage dans la lune, Le) ...
3409     4638                           Jurassic Park III (2001)
1057     1374             Star Trek II: The Wrath of Khan (1982)
5612    27032                     Who Am I? (Wo shi shei) (1998)
7901    95145  Dragon Ball: T

In [13]:
def verifica_relevantes(user_id,  recomendacoes, df_testing_path='data_spliting/testing.csv'):

    df_testing = pd.read_csv(df_testing_path)

    recomendacoes = recomendacoes.loc[:, 'movieId'].tolist()


    filmes_user_tansting = df_testing.loc[df_testing['userId'] == user_id]

    total = filmes_user_tansting.loc[:, 'movieId'].isin(filmes_user_tansting).sum()
    # O que queremos: dos filmes que RECOMENDEI, quantos estão no teste?
    total = pd.Series(recomendacoes).isin(filmes_user_tansting['movieId']).sum()

    print(f"O total de filmes para o {user_id} relevantes é de: {total}")

    return total
    


In [14]:
# from tqdm import tqdm

# # Criando um dicionário para guardar os scores de relevância (opcional, mas útil)
# relevancia_resultados = {}

# print("Verificando relevância das recomendações...")
# for user_id, recomendacao in tqdm(resultados.items()):
#     try:
#         # Chamando a sua função para cada usuário
#         # Assumindo que 'recomendacao' é o DataFrame retornado pela função anterior
#         total_relevante = verifica_relevantes(user_id, recomendacao)
        
#         # Armazenando o valor retornado (se você quiser analisar depois)
#         relevancia_resultados[user_id] = total_relevante
#     except Exception as e:
#         pass

total_relevante = verifica_relevantes(1, recomendados)

O total de filmes para o 1 relevantes é de: 0


In [56]:
# relevancia_resultados

# maior_valor = max(relevancia_resultados.values())
# print(maior_valor)

# melhor_chave = max(relevancia_resultados, key=relevancia_resultados.get)
# print(melhor_chave) # No seu exemplo, retornaria 20

testing = pd.read_csv('data_spliting/testing.csv')
traing = pd.read_csv('data_spliting/traing.csv')


testing = testing.loc[testing['userId'] == 1]
traing = traing.loc[traing['userId'] == 1]


testing.to_csv('validation/testing.csv',index=False)
traing.to_csv('validation/training.csv',index=False)

recomendacao = resultados[1]

recomendacao.to_csv('validation/recomendando.csv')